name: weather_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  location: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Black.ttf
        - asset: fonts/Rubik-BlackItalic.ttf
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-BoldItalic.ttf
        - asset: fonts/Rubik-ExtraBold.ttf
        - asset: fonts/Rubik-ExtraBoldItalic.ttf
        - asset: fonts/Rubik-Italic.ttf
        - asset: fonts/Rubik-Light.ttf
        - asset: fonts/Rubik-LightItalic.ttf
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-MediumItalic.ttf
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-SemiBold.ttf
        - asset: fonts/Rubik-SemiBoldItalic.ttf
